### ISSUE TITLE
Add support for access token authentication

### ISSUE THREAD

**Issue by Constantin07** [atlassian/go-artifactory#6]
At the moment the authentication supports API Key auth using "X-JFrog-Art-Api" header.

It would be nice to add support for access tokens (Authorization: Bearer) as it does support expiration feature.

Reason: Make it available here https://github.com/atlassian/terraform-provider-artifactory/tree/master/docs

References:
https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API
https://www.jfrog.com/confluence/display/ACC/Access+Tokens

**Comment by dillon-giacoppo** [comment]
Done in version 2. Already propagated to the terraform provider
